# Generated by Django 5.0.4 on 2024-04-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
