# Generated by Django 5.0.4 on 2024-04-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='passwd', max_length=100),
            preserve_default=False,
        ),
    ]
