# Generated by Django 5.0.4 on 2024-04-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mail',
            field=models.EmailField(default='gowrishvarma@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
