# Generated by Django 5.0.4 on 2024-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='gowrish', max_length=20),
            preserve_default=False,
        ),
    ]
