# Generated by Django 5.0.4 on 2024-04-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='adharNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='hobbies',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='phoneNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
