# Generated by Django 5.0.4 on 2024-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_register_address_alter_register_adharnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='end',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='register',
            name='start',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
